# Add your LinkedIn email ID and password. WARNING: KEEP THIS OFFLINE ON YOUR PC AND DO NOT COMMIT/UPLOAD.
email: test@gmail.com
password: test

# Anti-lock default is False to prevent your PC from sleeping to allow bot to run uninterrupted.
# Set it to True if you wish to disable this functionality.
disableAntiLock: True

# Set to True if you wish to search for remote jobs only.
remote: False

# Set to True if you wish to search for jobs marked as "under 10 applicants" (default is False).
lessthanTenApplicants: False

# Set to True or False to suit your preference. Multiple True allowed.
experienceLevel:
 internship: False
 entry: True
 associate: True
 mid-senior level: True
 director: False
 executive: False

# Set to True or False to suit your preference. Multiple True allowed.
jobTypes:
 full-time: True
 contract: True
 part-time: True
 temporary: True
 internship: False
 other: False
 volunteer: False

# Set ONLY one as True to suit your preference.
date:
 all time: True
 month: False
 week: False
 24 hours: False

# Remove hash sign to add positions. You can add as many as you need, but preserve formatting
positions:
 - Python
 - Software
 - Java
 - wordpress
 - Android
 - PHP
 - Liferay
 - Laravel
 #- ...

# Remove hash sign to add locations. You can add as many as you need including adding 'Remote' as a location but first location must be a valid country.
locations:
 - Remote
 #- First location
 #- A second location
 #- A third location
 #- ...
#  - Addis Ababa, Addis Ababa, Ethiopia
#  - Ethiopia

# Set to True if you are residing in the country of job
residentStatus: False

# Distance from the location added above. Allowed values are {0, 5, 10, 25, 50, 100}, use only one.
distance: 100

# Optional directory to save logs, does not work sometimes. Does not work sometimes, so leave it unchanged.
outputFileDirectory: /Users/macbookpro/Desktop/python/EasyApplyBotOutputFile/

# Companies you don't want to apply.
companyBlacklist:
#  - Crossover
#  - company
 #- company2

# Job titles you want to avoid applying. Use it to refine performance of bot.
titleBlacklist:
 #- word1
 #- word2

# Bot will not apply to jobs posted by black listed people.
posterBlacklist:
 #- name1
 #- name2

# Path to your CV/resume and cover letter (remove hash sign). These paths often don't work
# so apply one job manually once, bot will reuse manually uploaded CV for automating the task.
# Note: Prefer a path without spaces, i.e. instead of "Me My" to "MeMy" or "Me_My".
uploads:
 resume: /Users/macbookpro/Downloads/Resume.pdf
 # Cover letter is optional
 coverLetter: /Users/macbookpro/Downloads/CoverLettter.pdf


# ------------ QA section -------------------

# ------------ Additional parameters: checkboxes ---------------
checkboxes:
 # Do you have a valid driver's license? (yes/no checkbox)
 driversLicence: True
 # Will you now, or in the future, require sponsorship for employment visa status (e.g. H-1B visa status)? (yes/no checkbox)
 # This is relative to the location and your citizenship applying above, and same with legallyAuthorized.
 requireVisa: False
 # Are you legally authorized to work in COUNTRY? (yes/no checkbox)
 legallyAuthorized: True
 # Do you have necessary licenses or certifications required in your profession? E.g. CPA, CA, CFA, professional license
 certifiedProfessional: True
 # We must fill this position urgently. Can you start immediately? (yes/no checkbox)
 urgentFill: True
 # Are you comfortable commuting or work on-site to this job's location? (yes/no checkbox)
 commute: True
 # Are you comfortable working in a remote environment? (yes/no checkbox)
 remote: True
 # Are you comfortable taking a drug in accordance with local/state laws? (yes/no checkbox)
 drugTest: True
 # Are you willing to complete an assessment? (yes/no checkbox)
 assessment: True
 # Do you have security clearance of [xxx] country? (yes/no checkbox)
 securityClearance: False
 # Have you completed the following level of education: DEGREE TYPE? Remove applicable # signs (yes/no checkbox)
 degreeCompleted:
   - High School Diploma
   - Bachelor's Degree
   - Master's Degree
  # - Associate's Degree
  # - Master of Business Administration
  # - Doctor of Philosophy
  # - Doctor of Medicine
  # - Doctor of Law
 # Are you willing to undergo a background check, in accordance with local law/regulations?
 backgroundCheck: True
 Have you ever applied: False
 Are you located in the World?: True
 30days: True
 Mobile developer: True 
 
  

# ------------ Additional parameters: universityGpa ---------------
universityGpa: 3.33

# ------------ Additional parameters: salaryMinimum ---------------
salaryMinimum: 10000

# ------------ Additional parameters: languages ---------------
languages:
 english: Native or bilingual # Allowed choices { None, Conversational, Professional, Native or bilingual }
 # arabic: Conversational
 # french: Professional

# ------------ Additional parameters: noticePeriod in weeks ---------------
noticePeriod: 1

# ------------ Additional parameters: years of experience ---------------
# How many years of work experience do you have ...? (whole numbers only)
# You may add more skills depending on your industry or profession at the bottom.
experience:
 # normal ones
 Accounting/Auditing: 0
 Administrative : 0
 Advertising : 0
 Analyst : 0
 Art/Creative: 0
 Business Development: 0
 Consulting: 0
 Customer Service: 0
 Distribution Design: 0
 Education: 0
 Engineering: 3
 Finance: 0
 General Business: 0
 Health Care Provider: 0
 Human Resources: 0
 Information Technology: 5
 Legal: 0
 Management: 0
 Manufacturing: 0
 Marketing: 0
 Public Relations: 0
 Purchasing: 0
 Product Management: 2
 Project Management: 2
 Production: 0
 Quality Assurance: 2
 Research: 0
 Sales: 0
 Science: 0
 Strategy/Planning: 0
 Supply Chain: 0
 Training: 0
 Writing/Editing: 0
 VBA: 0
 PowerBI: 0
 PowerQuery: 0
 Excel: 0
 PowerPoint: 0
 Word: 0
 SQL Server: 3
 Communication: 0
 Financial markets: 0
 Business: 0
 Financial services: 0
 Team leadership: 0
 Cash flow: 0
 Hedging: 0
 Treasury services: 0
 Microsoft Power BI: 0
 Accounting: 0
 Auditing: 0
 Financial modeling: 0
 Budgeting & forecasting: 0
 FP&A: 0
 PQE: 0
 Training & Development: 0
 python: 4
 selenium: 3

 Docker: 3
 AWS: 3
 PHP: 4
 Software Engineer: 5
 Java: 4
 wordpress: 3
 java: 4
 Blockchain: 3
 Solidity: 1
 ethereum: 2
 
 Years of experience: 8
 C++: 0
 Javascript: 3
 Node: 0
 Spring Boot: 1
 Laravel: 2
 SASS: 0
 React: 0
 React Native: 0
 Django: 3
 SAP: 0
 ipt: 0
 MySQL: 4
 Shopify: 0
 Typescript: 0
 Angular: 0
 Redux.js: 0
 Angular Command Line Interface (CLI): 0
 C#: 0
 C (Programming Language): 0
 Software Development: 6
 Linux: 4
 Cross-functional team: 0
 Social media platforms: 0
 Microsoft Azure: 0
 .NET: 0
 #  How many hours are you available every week? Required
 Hours are you available every week: 40
 #  What is your desired hourly pay rate (in USD)? Required
 Hourly pay rate: 20
 #  Please evaluate on a scale from 1 to 10 you ability to manage technical issues on different social media platforms? Required
 Manage Technical Issues: 8
 # What are your salary requirements in gross monthly PLN?
 gross monthly PLN: 2000
 # how many years of work experience do you have with programming languages?
 programming languages: 5
 # how many years of work experience do you have with internet of things (iot)?
 internet of things (iot): 1
 # how many years of work experience do you have with opencv?
 opencv: 1
 # how many years of work experience do you have with numpy?
 numpy: 3
 Devops: 3
 # how many years of work experience do you have with user interface design?
 Interface Design: 1
 # how many years of work experience do you have with Embedded Software?
 Embedded software: 1
 # how many years of work experience do you have with apache?
 Apache: 6
 # how many years of work experience do you have with puppeteering?
 puppeteering: 0
 # how many years of work experience do you have with scorm?
 scorm: 0
 # how many years of work experience do you have with aicc?
 aicc: 0
 # how many years of work experience do you have with sql server integration services (ssis)?
 server integration services: 1
 # how many years of work experience do you have using google analytics?
 google analytics: 1
 # how many years of work experience do you have using instagram analytics?
 instagram analytics: 1
 # how many years of work experience do you have using facebook ads manager?
 facebook ads manager: 1
 # ui/ux experience / how many years of work experience do you have with [skill]? ui developer
 ui: 2
 ux: 2
 # how many years of work experience do you have with microservices?
 microservices: 2
 # how many years of work experience do you have with google material design?
 google material design: 3
 # ¿cuántos años de experiencia tienes con interfaces?
 interfaces: 1
 # how many years of work experience do you have with golang?
 Golang: 0
 # how many years of work experience do you have with kafka ?
 kafka: 0
 # how many years of work experience do you have with docker?
 Docker: 4
 # how many years of work experience do you have with ci/cd ?
 ci/cd: 4
 # quanti anni di esperienza di lavoro hai con supporto tecnico?
 supporto tecnico: 2
 # how many years of work experience do you have with android sdk?
 android sdk: 4
 # how many years of work experience do you have with microsoft office?
 microsoft office: 5
 # wie viele jahre erfahrung haben sie mit: national institute of standards and technology?
 national institute of standards and technology: 0
 # wie viele jahre erfahrung haben sie mit: cybersecurity?
 cybersecurity: 2
 # how many years of work experience do you have with saas development?
 saas: 3
 # how many years of work experience do you have with akka?
 akka: 0
 zoho: 0
 # how many years of work experience do you have with software defined networking?
 software defined networking: 1
 wordpress: 3
 # how many years of work experience do you have with ruby on rails?
 ruby: 0
 # how many years of work experience do you have with oracle forms?
 oracle forms: 0 
 # how many years of work experience do you have with weblogic?
 weblogic: 0
 kubuernetes: 0
 Symfony: 0 
 # experience in mobile development using xamarin
 Xamarin: 0
 # experience with search engines like solr
 Solr: 0
 experience working for a product company: Yes
 Skill development: 5
 # quanti anni di esperienza di lavoro hai con l’uso di visual studio?
 visual studio: 5
 # how many years of work experience do you have with spring?
 Spring: 0
 Gitlab: 1
 Graphic design: 1
 # how many years of work experience do you have with snowflake cloud?
 snowflake cloud: 0
 # how many years of technology, information and internet experience do you currently have?
 technology, information and internet experience: 5
 # how many years of work experience do you have with gis/spatial data?
 gis/spatial data: 0
 github: 5
 akeno: 0
 # how many years of work experience do you have in a start-up environment?
 Start-up: 3

 # default to put for any industry/skill that you did not list
 default: 2

# ------------ Additional parameters: personal info ---------------
personalInfo:
 Pronouns: Mr.
 First Name: Esubalew
 Last Name: Amenu
 Phone Country Code: Ethiopia (+251) # See Linkedin for your country code, must be exact according to the international platform, i.e. Italy (+39) not Italia (+39)
 Mobile Phone Number: 923481783
 Street address: Asmera road, w13
 City: Yeka subcity, Addis Ababa # Include the state/province as well!
 State: Addis Ababa
 Zip: 7599
 Linkedin: https://www.linkedin.com/in/esubalew-amenu/
 Website: https://github.com/esubalewamenu # github/website is interchangeable here
 MessageToManager: "Hi, I am interested to join your organization. Please have a look at my resume. Thank you." # Keep message short and within the quotes. This is a testing feature and may not work.

# ------------ Additional parameters: USA employment crap ---------------
eeo:
 gender: M
 race: None
 veteran: None
 disability: None
 citizenship: yes
 clearance: no
